# Generated by Django 3.2.6 on 2023-08-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_name', models.CharField(max_length=250, verbose_name='Task Name')),
                ('Task_status', models.BooleanField(default=False, verbose_name='Task Status')),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
