# Generated by Django 3.1.4 on 2023-08-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20230812_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='Date',
        ),
    ]
